name: bdt_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - pyyaml     
  - requests      
  - tqdm
  - typing_extensions
  - pip:
    - torch
    - torchvision
    - torchaudio
    - transformers
    - accelerate
    - bitsandbytes
    - huggingface_hub
    - regex
    - packaging
    - filelock
    - python-dotenv
    - ipykernel